import { FastifyPluginAsync } from 'fastify';
import fastifyPlugin from 'fastify-plugin';
import fastifySwagger from '@fastify/swagger';
import fastifySwaggerUi from '@fastify/swagger-ui';
import { withRefResolver } from 'fastify-zod';
import { env } from '@config/env';

const swaggerPlugin: FastifyPluginAsync = async (fastify) => {
  await fastify.register(
    fastifySwagger,
    withRefResolver({
      openapi: {
        info: {
          title: 'Fastify API',
          version: '0.1.0',
          description: 'Fastify API with autogenerated swagger documentation',
        },
        servers: [{ url: env.API_DOMAIN }],
      },
    })
  );

  await fastify.register(fastifySwaggerUi, {
    routePrefix: '/docs',
    staticCSP: true,
  });
};

export default fastifyPlugin(swaggerPlugin);
